.gitignore
streams-movie-demo/loader/src/main/groovy/RatedMoviesConsumer.groovy
streams-movie-demo/loader/src/main/groovy/consume.groovy
streams-movie-demo/loader/src/main/groovy/produce.groovy
streams-movie-demo/streams/src/main/java/io/confluent/demo/naive/StreamProcessingUsingConsumerProducer.java
streams-movie-demo/streams/src/main/java/io/confluent/demo/naive/StreamProcessingUsingKafkaStreams.java

Fixing few bits in streaming movie ratings demo.
Added naïve exaple of stream processing with producer and consumer vs kstreams

Streaming movies demo improvements

---

mysql-debezium-ksql-elasticsearch/docker-compose/docker-compose.yml

Did a very small change in YAML to upgrade Confluent Platform version to 5.1

Upgrading CP to 5.1 version

---

ksql-workshop/ksql-workshop.adoc

"Command" isn't part of the command so should be outside the highlight.

Fix code highlighting

---

twitter-streams-operator/.gitignore
twitter-streams-operator/README.adoc
twitter-streams-operator/common/Makefile
twitter-streams-operator/common/bin/retry.sh
twitter-streams-operator/common/cfg/serviceaccount-tiller.yaml
twitter-streams-operator/demo.ksql
twitter-streams-operator/docker/Dockerfile
twitter-streams-operator/docker/build.sh
twitter-streams-operator/gke-base/Makefile
twitter-streams-operator/gke-base/cfg/clicks-datagen-connector-configmap.yaml
twitter-streams-operator/gke-base/cfg/clicks-datagen-connector-deploy-job.yaml
twitter-streams-operator/gke-base/cfg/client-console-pod.yaml
twitter-streams-operator/gke-base/cfg/kafka-client-secrets.yaml
twitter-streams-operator/gke-base/cfg/twitter-connector-deploy-job.yaml
twitter-streams-operator/gke-base/cfg/twitter-connector-secret.yaml
twitter-streams-operator/gke-base/cfg/values.yaml

Twitter streams demo from kafka summit 2019

☸️ Kafka Summit SF 2019 demo

---

pacman-ccloud/pacman/game/js/game.js
pacman-ccloud/terraform/aws/compute.tf
pacman-ccloud/terraform/aws/functions.tf
pacman-ccloud/terraform/aws/functions/.gitignore
pacman-ccloud/terraform/aws/functions/build.sh
pacman-ccloud/terraform/aws/functions/pom.xml
pacman-ccloud/terraform/aws/functions/sample.json
pacman-ccloud/terraform/aws/functions/src/main/java/io/confluent/cloud/pacman/EventHandler.java
pacman-ccloud/terraform/aws/functions/src/main/resources/logback.xml
pacman-ccloud/terraform/aws/networking.tf
pacman-ccloud/terraform/aws/outputs.tf
pacman-ccloud/terraform/aws/pacman.tf
pacman-ccloud/terraform/aws/userdata.tf
pacman-ccloud/terraform/aws/variables.tf
pacman-ccloud/terraform/azr/compute.tf
pacman-ccloud/terraform/azr/pacman.tf
pacman-ccloud/terraform/azr/variables.tf
pacman-ccloud/terraform/gcp/pacman.tf

This PR aims to remove completely the need to spin up EC2 instances and ELB's for things like REST Proxy. Instead, the code now declares API Gateways that will front the requests coming from the S3 bucket, and process the events using a lambda function.

Making the AWS Implementation Completely Serverless

---

tiered-storage/scripts/jmx_metrics.sh

Fix jmx metrics query for tier fetcher

---

tiered-storage/README.md
tiered-storage/docker-compose.yml

Adding consumer config to volumes of docker-compose

Add consumer config

---

ksummit-operator-demo/README.adoc
ksummit-operator-demo/aws/aws.yaml
ksummit-operator-demo/aws/config
ksummit-operator-demo/aws/consumer.properties
ksummit-operator-demo/aws/kafka.properties
ksummit-operator-demo/gcp/config
ksummit-operator-demo/gcp/gcp.yaml
ksummit-operator-demo/gcp/kafka.properties
ksummit-operator-demo/gcp/producer.properties
ksummit-operator-demo/gcp/replicator.json
ksummit-operator-demo/scratchpad
ksummit-operator-demo/scripts/client.sh
ksummit-operator-demo/scripts/createKeystore.sh
ksummit-operator-demo/scripts/createTrustStore.sh
ksummit-operator-demo/scripts/validateKafkaCluster.sh

Cluster in EKS replicated to GCP using Replicator

WIP KSummit NYC demo

---

build-a-streaming-pipeline/workshop/02_workshop.adoc

It was displaying mysql_to_kafka.gif instead.

Add correct stream_table picture

---

README.md
cluster-linking/README.md
cluster-linking/docker-compose.yml
cluster-linking/scripts/2-create-links-topics.sh
cluster-linking/scripts/3-list-links-and-lag.sh
cluster-linking/scripts/4-run-consumer.sh
cluster-linking/scripts/5-run-producer.sh
cluster-linking/scripts/6-setup-consumer.sh
cluster-linking/scripts/7-migrate-one-cg.sh
cluster-linking/scripts/8-stop-link.sh
cluster-linking/scripts/9-shutdown.sh

Add cluster linking demo to demo scene

---

README.md

@addisonhuddy WDYT? Have I grouped the correct demos here, and is the heading ok?

Split CP demos into separate subheading

---

cluster-linking/scripts/7-migrate-one-cg.sh
cluster-linking/scripts/9-shutdown.sh

Remove unused pumba-latency reference, add "#" to bin/bash line at top of one file

Nitpicks to cluster linking demo

---

cluster-linking/scripts/5-run-producer.sh
cluster-linking/scripts/7-migrate-one-cg.sh
cluster-linking/scripts/9-shutdown.sh

small changes to the cluster linking demo to make it easier to run

small changes to make running the demo easier

---

cluster-linking/docker-compose.yml

- Update Cluster Linking demo to pull Docker images from specific release, 6.0.0
cc: @addisonhuddy , @rmoff 
Signed-off-by: Victoria Bialas <vicky@confluent.io>

DOCS-5513 Pin Cluster Linking demo to CP 6.0.0 release

---

tiered-storage/README.md

fixed incorrect port in readme consumer command

updated readme to fix incorrect port

---

sonos/docker-compose.yml

Fixed the docker-compose to reference public repos for the sonos demo.

Fixed the docker-compose to reference public repos.

---

LICENSE

added apache v2 license

---

connect-jdbc/docker-compose.yml

Remove deprecated internal converters for connect.

remove_deprecated_converters

---

ibm-demo/mqlibs/README.md

There is no 2 without 3 they say... :)

Create README.md in IBM Demo mqlibs folder

---

README.md
gen-test-data/datagen/docker-compose.yml
gen-test-data/voluble/docker-compose.yml
python-microservices/README.adoc
python-microservices/cheese-service/config.properties
python-microservices/cheese-service/main.py
python-microservices/cheese-service/poetry.lock
python-microservices/cheese-service/pyproject.toml
python-microservices/meat-service/config.properties
python-microservices/meat-service/main.py
python-microservices/meat-service/poetry.lock
python-microservices/meat-service/pyproject.toml
python-microservices/pizza-service/app.py
python-microservices/pizza-service/config.properties
python-microservices/pizza-service/pizza.py
python-microservices/pizza-service/pizza_service.py
python-microservices/pizza-service/poetry.lock
python-microservices/pizza-service/pyproject.toml
python-microservices/sauce-service/config.properties
python-microservices/sauce-service/main.py
python-microservices/sauce-service/poetry.lock
python-microservices/sauce-service/pyproject.toml
python-microservices/veggie-service/config.properties
python-microservices/veggie-service/main.py
python-microservices/veggie-service/poetry.lock
python-microservices/veggie-service/pyproject.toml

Adding the demo project for the PyTexas conference.

Add Python Microservices project

---

confluent-ais-demo/README.md
confluent-connector-github-demo/README.md
confluent-xml-demo/README.md

adding a few new demos for the confluent developer demo page.

add READMEs with demo tutorials

---

confluent-kafka-javascript-basic/README.md
confluent-kafka-javascript-basic/consumer.js
confluent-kafka-javascript-basic/package.json
confluent-kafka-javascript-basic/producer.js
confluent-kafka-javascript-basic/sample.env
confluent-kafka-javascript-poll/.gitignore
confluent-kafka-javascript-poll/README.md
confluent-kafka-javascript-poll/consumer.js
confluent-kafka-javascript-poll/index.html
confluent-kafka-javascript-poll/package.json
confluent-kafka-javascript-poll/producer.js
confluent-kafka-javascript-poll/seedproducer.js

adding a basic js client demo and a slightly more advanced version

adding 2 new js client demos

---

confluent-kafka-javascript-poll/README.md

remove url

---

livestreams/october-6/websockets-ksqldb/build.gradle
livestreams/september-15/build.gradle
livestreams/september-22/build.gradle

Remove s3 refs

---

spring-into-kafka-cc/README.adoc
spring-into-kafka-cc/build.gradle.kts
spring-into-kafka-cc/common/build.gradle.kts
spring-into-kafka-cc/common/src/main/avro/checkin.avsc
spring-into-kafka-cc/common/src/main/avro/enriched-checkin.avsc
spring-into-kafka-cc/common/src/main/avro/member.avsc
spring-into-kafka-cc/common/src/main/avro/membership-level.avsc
spring-into-kafka-cc/common/src/main/kotlin/io/confluent/devrel/spring/kfaker/BaseKFaker.kt
spring-into-kafka-cc/gradle.properties
spring-into-kafka-cc/kafka-streams/README.adoc
spring-into-kafka-cc/kafka-streams/build.gradle.kts
spring-into-kafka-cc/kafka-streams/src/main/kotlin/io/confluent/devrel/springcc/streams/MyStreamsApp.kt
spring-into-kafka-cc/kafka-streams/src/main/kotlin/io/confluent/devrel/springcc/streams/WordCountProcessor.kt
spring-into-kafka-cc/kafka-streams/src/main/kotlin/io/confluent/devrel/springcc/streams/WordCountRestController.kt
spring-into-kafka-cc/kafka-streams/src/main/kotlin/io/confluent/devrel/springcc/streams/checkins/ClubConfiguration.kt
spring-into-kafka-cc/kafka-streams/src/main/kotlin/io/confluent/devrel/springcc/streams/checkins/MemberCheckinProcessor.kt
spring-into-kafka-cc/kafka-streams/src/main/resources/application.yml
spring-into-kafka-cc/kafka-streams/src/test/kotlin/io/confluent/devrel/springcc/streams/WordCountProcessorUnitTest.kt
spring-into-kafka-cc/kafka-streams/src/test/kotlin/io/confluent/devrel/springcc/streams/checkins/MemberCheckinProcessorUnitTest.kt
spring-into-kafka-cc/settings.gradle.kts
spring-into-kafka-cc/terraform/checkin-topic-schema.tf
spring-into-kafka-cc/terraform/enriched-checkin-topic-schema.tf
spring-into-kafka-cc/terraform/membership-topic-schema.tf
spring-into-kafka-cc/terraform/outputs.tf
spring-into-kafka-cc/terraform/wordcount-topics.tf

* Correcting command on terraform output to env file.
* new protobuf object definitions
* initial commit of cloud-stream-kafka
* new topics for kafka streams example
* abandoning protobuf for avro.
* simple kafka streams topology, filter platinum.
* Kafka-streams example.
* Update topology for only platinum and gold members.
* documentation and word count topics in terraform.
* Updates to README from code review
---------

Spring into CC with Kotlin Volume 2 - Kafka Streams(#3)

---

flink-streamlit/kafkaproducer.py

Removed the hard-coded bootstrap server, as people have run into difficulties due to the hard-coding. 
I did not add it to the Streamlit secret env as it's not a secret.

remove hard-coded bootstrap
